### ISSUE TITLE
High availability installation not working

### ISSUE THREAD

**Issue by shen3lu4** [goharbor/harbor-helm#146]
I am trying to add high availability based on the doc https://github.com/goharbor/harbor-helm/blob/master/docs/High%20Availability.md. 

I first installed a single replica instance of v1.7.1 and verified that it is working. For that installation, I have set `persistence.persistentVolumeClaim.registry.accessMode`, `persistence.persistentVolumeClaim.chartmuseum.accessMode` and `persistence.persistentVolumeClaim.jobservice.accessMode` to `ReadWriteMany`.

Then I changed values.yaml and set `portal.replicas`, `adminserver.replicas`, `core.replicas`, `jobservice.replicas`, `registry.replicas`, `chartmuseum.replicas`, `clair.replicas`, `notary.server.replicas` and `notary.signer.replicas` to 2. I then ran 'helm upgrade'. The upgrade was completed without errors.

However, the harbor application now shows an error "We are unable to perform your action because internal server errors have occurred."  

I found two containers with errors in the logs:
--notary-server:
{"level":"error","msg":"Trust not fully operational: rpc error: code = 13 desc = connection error: desc = \"transport: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"harbor-notary-ca\\\")\"","time":"2019-01-22T19:35:01Z"}

--database:
ERROR:  duplicate key value violates unique constraint "lock_name_key"
DETAIL:  Key (name)=(updater) already exists.
STATEMENT:  INSERT INTO Lock(name, owner, until) VALUES($1, $2, $3)

**Comment by ywk253100** [comment]
@shen3lu4 If you just want to change the `replicas` of the pod, you should use `kubectl scale` rather than `kubectl upgrade`.

The reason for error `We are unable to perform your action because internal server errors have occurred` is that when you running upgrade the pod didn't read the new `configmap`, it is has been fixed in master branch by #140.

And the error you got from notary-server is another issue, we'll check it.

**Comment by shen3lu4** [comment]
@ywk253100 Thanks for your reply. I am using "helm update" not "kubectl update" after changing the replicas in values.yml in the helm chart. Is that not the right way to do it?

**Comment by ywk253100** [comment]
To avoid the error you got, you can try
1. Delete the old deployment and deploy the chart with `replicas=2` directly
or
2. Use the `kubectl scale` to change the replicas

This two ways should both work, and we'll check the error got when running `helm upgrade` and find what happpened

**Comment by shen3lu4** [comment]
I deleted everything including the pvc and reinstalled from scratch with
replicas=2 directly. I still see the same errors:

--notary-server (error only in one of the notary-server pods):
2019/01/24 22:10:02 grpc: addrConn.resetTransport failed to create client
transport: connection error: desc = "transport: dial tcp 10.102.100.236:7899:
getsockopt: connection refused"; Reconnecting to
{ht-harbor-notary-signer:7899 <nil>}

--database:
ERROR:  duplicate key value violates unique constraint "lock_name_key"
DETAIL:  Key (name)=(updater) already exists.
STATEMENT:  INSERT INTO Lock(name, owner, until) VALUES($1, $2, $3)
LOG:  incomplete startup packet

**Comment by shen3lu4** [comment]
@ywk253100 
Yes it looks like the error in one of the notary-server container only comes when starting up. So this is not an issue of concern.

I still see this error in database though: 
ERROR:  duplicate key value violates unique constraint "lock_name_key"
DETAIL:  Key (name)=(updater) already exists.
STATEMENT:  INSERT INTO Lock(name, owner, until) VALUES($1, $2, $3)

The application seems to be functional.

**Comment by ywk253100** [comment]
The error can be ignored, it is caused by that multiple instances try to update the schema and some of them lock the table.
